---
galaxy_info:
  author: HybridOps.Studio
  description: Join host to Active Directory domain
  license: MIT
  min_ansible_version: "2.12"
  platforms:
  - name: Windows
    versions: [ "2019", "2022" ]
dependencies: []
